CATEGORY = 'category'
CATEGORY_NAME = 'name'
COST = 'cost'
CURRENCY_CODE = 'currency_code'
CREATED_AT = 'created_at'
CREATED_BY = 'created_by'
CREATED_BY_NAME = 'first_name'
CREATED_BY_ID = 'id'
UPDATED_AT = 'updated_at'
DESC = 'description'
GROUP_ID = 'group_id'
ID = 'id'
REPAYMENTS = 'repayments'
REPAYMENTS_AMOUNT = 'amount'
REPAYMENTS_FROM = 'from'
REPAYMENTS_TO = 'to'
ID_YASH = 32703372
ID_MEET = 43357520
ID_SWAPNIL = 46379417
ID_GEET = 27555627
ID_AKSHAY = 41535264
EXPENSES = 'expenses'
USERS = 'users'
USER = 'user'
USER_FIRST_NAME = 'first_name'
USER_ID = 'id'
USER_NET_BALANCE = 'net_balance'
USER_OWED_SHARE = 'owed_share'
USER_PAID_SHARE = 'paid_share'
UTF8 = 'utf-8'

NUM_MONTHS = 12
TIME_SLEEP = 10
LIMIT = 1000

JANUARY = 'January'
FEBRUARY = 'February'
MARCH = 'March'
APRIL = 'April'
MAY = 'May'
JUNE = 'June'
JULY = 'July'
AUGUST = 'August'
SEPTEMBER = 'September'
OCTOBER = 'October'
NOVEMBER = 'November'
DECEMBER = 'December'

ARR_MONTHS = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
              'November', 'December']
